version: '3.1'
services:
  proxy:
    depends_on:
      - main
      - child
    image: nginx
    container_name: proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend-not-found.html:/var/www/html/backend-not-found.html:ro
    ports:
      - 80:80

  admin:
    depends_on:
      - db-wordpress
    image: wordpress
    container_name: wp-admin
    restart: always
    volumes:
      - ./data/wp-admin:/var/www/html
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_HOST: db-wordpress:3306
      WORDPRESS_DB_NAME: wpadmin
      VIRTUAL_HOST: admin.wordpress.dev

  main:
    depends_on:
      - db-wordpress
    image: wordpress
    container_name: wp-main
    restart: always
    volumes:
      - ./data/wp-main:/var/www/html
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_HOST: db-wordpress:3306
      WORDPRESS_DB_NAME: wpmain
      VIRTUAL_HOST: main.wordpress.dev

  child:
    depends_on:
      - db-wordpress
    image: wordpress
    container_name: wp-child
    restart: always
    volumes:
      - ./data/wp-child:/var/www/html
    environment:
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_HOST: db-wordpress:3306
      WORDPRESS_DB_NAME: wpchild
      VIRTUAL_HOST: child.wordpress.dev

  db-wordpress:
    image: mysql
    container_name: db-wordpress
    restart: always
    volumes:
      - ./db-wordpress:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
